### ISSUE TITLE
Examples: Rewrite pyroscope golang pull integration

### ISSUE THREAD

**Issue by thisisobate** [pyroscope-io/pyroscope#1074] opened 2022-04-29 12:38 UTC
### Problem
The current draft for the golang-pull integration is not in its best form. Readers, most especially beginners, find it hard to 
read and understand. 

### Expectation
Rewrite blogpost for better readability.

**Comment by Rperry2174** [comment] 2022-05-03 17:36
closing as i believe this is a duplicate of #733 .. feel free to add any more info there

**Closed by Rperry2174** 2022-05-03 17:36 UTC
